#Code generated by ChatGPT modified by Benjamin Moshirian
import math
import csv
import os

# Set your reference position here
center_lat = -19.267396     # Example: San Francisco latitude
center_lon = 147.055679   # Example: San Francisco longitude

radius_m = 5.0      # radius in meters
spacing_m = 0.5     # spacing between points in meters

# Earth's radius in meters
EARTH_RADIUS = 6378137

# Converts meters to degrees latitude
def meters_to_lat(meters):
    return meters / 111320  # 1 deg latitude ≈ 111.32 km

# Converts meters to degrees longitude, adjusted by latitude
def meters_to_lon(meters, latitude):
    return meters / (111320 * math.cos(math.radians(latitude)))

# Generate points in a circle
points = []

r = 0.0
patch_decision = 2
ping_depth = 1000
patch_id = 1
while r <= radius_m:
    circumference = 2 * math.pi * r if r != 0 else 1
    num_points = max(1, int(circumference / spacing_m))
    for i in range(num_points):
        angle = (2 * math.pi / num_points) * i
        dx = r * math.cos(angle)
        dy = r * math.sin(angle)
        
        dlat = meters_to_lat(dy)
        dlon = meters_to_lon(dx, center_lat)
        
        lat = center_lat + dlat
        lon = center_lon + dlon
        
        points.append((center_lat,center_lon,lat, lon, patch_decision,ping_depth,patch_id))
    r += spacing_m

# Save to CSV
output_dir = "generatedTestPoints"
os.makedirs(output_dir,exist_ok=True)
output_file = os.path.join(output_dir, "gnss_points_test_site_01.csv")
with open(output_file, mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(["center_lat","center_lon","patch_lat", "patch_lon","patch_decision","ping_depth","patch_id"])
    writer.writerows(points)

print(f"Generated {len(points)} points and saved to {output_file}")
